// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/resources/MsgProto.proto

package com.yahoo.ycsb.db.voldemort;

public final class MsgProto {
  private MsgProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface MsgOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // repeated .com.yahoo.ycsb.db.voldemort.Entry entry = 1;
    /**
     * <code>repeated .com.yahoo.ycsb.db.voldemort.Entry entry = 1;</code>
     */
    java.util.List<com.yahoo.ycsb.db.voldemort.MsgProto.Entry> 
        getEntryList();
    /**
     * <code>repeated .com.yahoo.ycsb.db.voldemort.Entry entry = 1;</code>
     */
    com.yahoo.ycsb.db.voldemort.MsgProto.Entry getEntry(int index);
    /**
     * <code>repeated .com.yahoo.ycsb.db.voldemort.Entry entry = 1;</code>
     */
    int getEntryCount();
    /**
     * <code>repeated .com.yahoo.ycsb.db.voldemort.Entry entry = 1;</code>
     */
    java.util.List<? extends com.yahoo.ycsb.db.voldemort.MsgProto.EntryOrBuilder> 
        getEntryOrBuilderList();
    /**
     * <code>repeated .com.yahoo.ycsb.db.voldemort.Entry entry = 1;</code>
     */
    com.yahoo.ycsb.db.voldemort.MsgProto.EntryOrBuilder getEntryOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code com.yahoo.ycsb.db.voldemort.Msg}
   */
  public static final class Msg extends
      com.google.protobuf.GeneratedMessage
      implements MsgOrBuilder {
    // Use Msg.newBuilder() to construct.
    private Msg(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Msg(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Msg defaultInstance;
    public static Msg getDefaultInstance() {
      return defaultInstance;
    }

    public Msg getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Msg(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                entry_ = new java.util.ArrayList<com.yahoo.ycsb.db.voldemort.MsgProto.Entry>();
                mutable_bitField0_ |= 0x00000001;
              }
              entry_.add(input.readMessage(com.yahoo.ycsb.db.voldemort.MsgProto.Entry.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          entry_ = java.util.Collections.unmodifiableList(entry_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.yahoo.ycsb.db.voldemort.MsgProto.internal_static_com_yahoo_ycsb_db_voldemort_Msg_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.yahoo.ycsb.db.voldemort.MsgProto.internal_static_com_yahoo_ycsb_db_voldemort_Msg_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.yahoo.ycsb.db.voldemort.MsgProto.Msg.class, com.yahoo.ycsb.db.voldemort.MsgProto.Msg.Builder.class);
    }

    public static com.google.protobuf.Parser<Msg> PARSER =
        new com.google.protobuf.AbstractParser<Msg>() {
      public Msg parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Msg(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Msg> getParserForType() {
      return PARSER;
    }

    // repeated .com.yahoo.ycsb.db.voldemort.Entry entry = 1;
    public static final int ENTRY_FIELD_NUMBER = 1;
    private java.util.List<com.yahoo.ycsb.db.voldemort.MsgProto.Entry> entry_;
    /**
     * <code>repeated .com.yahoo.ycsb.db.voldemort.Entry entry = 1;</code>
     */
    public java.util.List<com.yahoo.ycsb.db.voldemort.MsgProto.Entry> getEntryList() {
      return entry_;
    }
    /**
     * <code>repeated .com.yahoo.ycsb.db.voldemort.Entry entry = 1;</code>
     */
    public java.util.List<? extends com.yahoo.ycsb.db.voldemort.MsgProto.EntryOrBuilder> 
        getEntryOrBuilderList() {
      return entry_;
    }
    /**
     * <code>repeated .com.yahoo.ycsb.db.voldemort.Entry entry = 1;</code>
     */
    public int getEntryCount() {
      return entry_.size();
    }
    /**
     * <code>repeated .com.yahoo.ycsb.db.voldemort.Entry entry = 1;</code>
     */
    public com.yahoo.ycsb.db.voldemort.MsgProto.Entry getEntry(int index) {
      return entry_.get(index);
    }
    /**
     * <code>repeated .com.yahoo.ycsb.db.voldemort.Entry entry = 1;</code>
     */
    public com.yahoo.ycsb.db.voldemort.MsgProto.EntryOrBuilder getEntryOrBuilder(
        int index) {
      return entry_.get(index);
    }

    private void initFields() {
      entry_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      for (int i = 0; i < getEntryCount(); i++) {
        if (!getEntry(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < entry_.size(); i++) {
        output.writeMessage(1, entry_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < entry_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, entry_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.yahoo.ycsb.db.voldemort.MsgProto.Msg parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.yahoo.ycsb.db.voldemort.MsgProto.Msg parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.yahoo.ycsb.db.voldemort.MsgProto.Msg parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.yahoo.ycsb.db.voldemort.MsgProto.Msg parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.yahoo.ycsb.db.voldemort.MsgProto.Msg parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.yahoo.ycsb.db.voldemort.MsgProto.Msg parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.yahoo.ycsb.db.voldemort.MsgProto.Msg parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.yahoo.ycsb.db.voldemort.MsgProto.Msg parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.yahoo.ycsb.db.voldemort.MsgProto.Msg parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.yahoo.ycsb.db.voldemort.MsgProto.Msg parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.yahoo.ycsb.db.voldemort.MsgProto.Msg prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.yahoo.ycsb.db.voldemort.Msg}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.yahoo.ycsb.db.voldemort.MsgProto.MsgOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.yahoo.ycsb.db.voldemort.MsgProto.internal_static_com_yahoo_ycsb_db_voldemort_Msg_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.yahoo.ycsb.db.voldemort.MsgProto.internal_static_com_yahoo_ycsb_db_voldemort_Msg_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.yahoo.ycsb.db.voldemort.MsgProto.Msg.class, com.yahoo.ycsb.db.voldemort.MsgProto.Msg.Builder.class);
      }

      // Construct using com.yahoo.ycsb.db.voldemort.MsgProto.Msg.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getEntryFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        if (entryBuilder_ == null) {
          entry_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          entryBuilder_.clear();
        }
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.yahoo.ycsb.db.voldemort.MsgProto.internal_static_com_yahoo_ycsb_db_voldemort_Msg_descriptor;
      }

      public com.yahoo.ycsb.db.voldemort.MsgProto.Msg getDefaultInstanceForType() {
        return com.yahoo.ycsb.db.voldemort.MsgProto.Msg.getDefaultInstance();
      }

      public com.yahoo.ycsb.db.voldemort.MsgProto.Msg build() {
        com.yahoo.ycsb.db.voldemort.MsgProto.Msg result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.yahoo.ycsb.db.voldemort.MsgProto.Msg buildPartial() {
        com.yahoo.ycsb.db.voldemort.MsgProto.Msg result = new com.yahoo.ycsb.db.voldemort.MsgProto.Msg(this);
        int from_bitField0_ = bitField0_;
        if (entryBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            entry_ = java.util.Collections.unmodifiableList(entry_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.entry_ = entry_;
        } else {
          result.entry_ = entryBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.yahoo.ycsb.db.voldemort.MsgProto.Msg) {
          return mergeFrom((com.yahoo.ycsb.db.voldemort.MsgProto.Msg)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.yahoo.ycsb.db.voldemort.MsgProto.Msg other) {
        if (other == com.yahoo.ycsb.db.voldemort.MsgProto.Msg.getDefaultInstance()) return this;
        if (entryBuilder_ == null) {
          if (!other.entry_.isEmpty()) {
            if (entry_.isEmpty()) {
              entry_ = other.entry_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureEntryIsMutable();
              entry_.addAll(other.entry_);
            }
            onChanged();
          }
        } else {
          if (!other.entry_.isEmpty()) {
            if (entryBuilder_.isEmpty()) {
              entryBuilder_.dispose();
              entryBuilder_ = null;
              entry_ = other.entry_;
              bitField0_ = (bitField0_ & ~0x00000001);
              entryBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getEntryFieldBuilder() : null;
            } else {
              entryBuilder_.addAllMessages(other.entry_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        for (int i = 0; i < getEntryCount(); i++) {
          if (!getEntry(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.yahoo.ycsb.db.voldemort.MsgProto.Msg parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.yahoo.ycsb.db.voldemort.MsgProto.Msg) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // repeated .com.yahoo.ycsb.db.voldemort.Entry entry = 1;
      private java.util.List<com.yahoo.ycsb.db.voldemort.MsgProto.Entry> entry_ =
        java.util.Collections.emptyList();
      private void ensureEntryIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          entry_ = new java.util.ArrayList<com.yahoo.ycsb.db.voldemort.MsgProto.Entry>(entry_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          com.yahoo.ycsb.db.voldemort.MsgProto.Entry, com.yahoo.ycsb.db.voldemort.MsgProto.Entry.Builder, com.yahoo.ycsb.db.voldemort.MsgProto.EntryOrBuilder> entryBuilder_;

      /**
       * <code>repeated .com.yahoo.ycsb.db.voldemort.Entry entry = 1;</code>
       */
      public java.util.List<com.yahoo.ycsb.db.voldemort.MsgProto.Entry> getEntryList() {
        if (entryBuilder_ == null) {
          return java.util.Collections.unmodifiableList(entry_);
        } else {
          return entryBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .com.yahoo.ycsb.db.voldemort.Entry entry = 1;</code>
       */
      public int getEntryCount() {
        if (entryBuilder_ == null) {
          return entry_.size();
        } else {
          return entryBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .com.yahoo.ycsb.db.voldemort.Entry entry = 1;</code>
       */
      public com.yahoo.ycsb.db.voldemort.MsgProto.Entry getEntry(int index) {
        if (entryBuilder_ == null) {
          return entry_.get(index);
        } else {
          return entryBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .com.yahoo.ycsb.db.voldemort.Entry entry = 1;</code>
       */
      public Builder setEntry(
          int index, com.yahoo.ycsb.db.voldemort.MsgProto.Entry value) {
        if (entryBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureEntryIsMutable();
          entry_.set(index, value);
          onChanged();
        } else {
          entryBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .com.yahoo.ycsb.db.voldemort.Entry entry = 1;</code>
       */
      public Builder setEntry(
          int index, com.yahoo.ycsb.db.voldemort.MsgProto.Entry.Builder builderForValue) {
        if (entryBuilder_ == null) {
          ensureEntryIsMutable();
          entry_.set(index, builderForValue.build());
          onChanged();
        } else {
          entryBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.yahoo.ycsb.db.voldemort.Entry entry = 1;</code>
       */
      public Builder addEntry(com.yahoo.ycsb.db.voldemort.MsgProto.Entry value) {
        if (entryBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureEntryIsMutable();
          entry_.add(value);
          onChanged();
        } else {
          entryBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .com.yahoo.ycsb.db.voldemort.Entry entry = 1;</code>
       */
      public Builder addEntry(
          int index, com.yahoo.ycsb.db.voldemort.MsgProto.Entry value) {
        if (entryBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureEntryIsMutable();
          entry_.add(index, value);
          onChanged();
        } else {
          entryBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .com.yahoo.ycsb.db.voldemort.Entry entry = 1;</code>
       */
      public Builder addEntry(
          com.yahoo.ycsb.db.voldemort.MsgProto.Entry.Builder builderForValue) {
        if (entryBuilder_ == null) {
          ensureEntryIsMutable();
          entry_.add(builderForValue.build());
          onChanged();
        } else {
          entryBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.yahoo.ycsb.db.voldemort.Entry entry = 1;</code>
       */
      public Builder addEntry(
          int index, com.yahoo.ycsb.db.voldemort.MsgProto.Entry.Builder builderForValue) {
        if (entryBuilder_ == null) {
          ensureEntryIsMutable();
          entry_.add(index, builderForValue.build());
          onChanged();
        } else {
          entryBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.yahoo.ycsb.db.voldemort.Entry entry = 1;</code>
       */
      public Builder addAllEntry(
          java.lang.Iterable<? extends com.yahoo.ycsb.db.voldemort.MsgProto.Entry> values) {
        if (entryBuilder_ == null) {
          ensureEntryIsMutable();
          super.addAll(values, entry_);
          onChanged();
        } else {
          entryBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .com.yahoo.ycsb.db.voldemort.Entry entry = 1;</code>
       */
      public Builder clearEntry() {
        if (entryBuilder_ == null) {
          entry_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          entryBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .com.yahoo.ycsb.db.voldemort.Entry entry = 1;</code>
       */
      public Builder removeEntry(int index) {
        if (entryBuilder_ == null) {
          ensureEntryIsMutable();
          entry_.remove(index);
          onChanged();
        } else {
          entryBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .com.yahoo.ycsb.db.voldemort.Entry entry = 1;</code>
       */
      public com.yahoo.ycsb.db.voldemort.MsgProto.Entry.Builder getEntryBuilder(
          int index) {
        return getEntryFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .com.yahoo.ycsb.db.voldemort.Entry entry = 1;</code>
       */
      public com.yahoo.ycsb.db.voldemort.MsgProto.EntryOrBuilder getEntryOrBuilder(
          int index) {
        if (entryBuilder_ == null) {
          return entry_.get(index);  } else {
          return entryBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .com.yahoo.ycsb.db.voldemort.Entry entry = 1;</code>
       */
      public java.util.List<? extends com.yahoo.ycsb.db.voldemort.MsgProto.EntryOrBuilder> 
           getEntryOrBuilderList() {
        if (entryBuilder_ != null) {
          return entryBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(entry_);
        }
      }
      /**
       * <code>repeated .com.yahoo.ycsb.db.voldemort.Entry entry = 1;</code>
       */
      public com.yahoo.ycsb.db.voldemort.MsgProto.Entry.Builder addEntryBuilder() {
        return getEntryFieldBuilder().addBuilder(
            com.yahoo.ycsb.db.voldemort.MsgProto.Entry.getDefaultInstance());
      }
      /**
       * <code>repeated .com.yahoo.ycsb.db.voldemort.Entry entry = 1;</code>
       */
      public com.yahoo.ycsb.db.voldemort.MsgProto.Entry.Builder addEntryBuilder(
          int index) {
        return getEntryFieldBuilder().addBuilder(
            index, com.yahoo.ycsb.db.voldemort.MsgProto.Entry.getDefaultInstance());
      }
      /**
       * <code>repeated .com.yahoo.ycsb.db.voldemort.Entry entry = 1;</code>
       */
      public java.util.List<com.yahoo.ycsb.db.voldemort.MsgProto.Entry.Builder> 
           getEntryBuilderList() {
        return getEntryFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          com.yahoo.ycsb.db.voldemort.MsgProto.Entry, com.yahoo.ycsb.db.voldemort.MsgProto.Entry.Builder, com.yahoo.ycsb.db.voldemort.MsgProto.EntryOrBuilder> 
          getEntryFieldBuilder() {
        if (entryBuilder_ == null) {
          entryBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              com.yahoo.ycsb.db.voldemort.MsgProto.Entry, com.yahoo.ycsb.db.voldemort.MsgProto.Entry.Builder, com.yahoo.ycsb.db.voldemort.MsgProto.EntryOrBuilder>(
                  entry_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          entry_ = null;
        }
        return entryBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:com.yahoo.ycsb.db.voldemort.Msg)
    }

    static {
      defaultInstance = new Msg(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.yahoo.ycsb.db.voldemort.Msg)
  }

  public interface EntryOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required bytes key = 1;
    /**
     * <code>required bytes key = 1;</code>
     */
    boolean hasKey();
    /**
     * <code>required bytes key = 1;</code>
     */
    com.google.protobuf.ByteString getKey();

    // required bytes value = 2;
    /**
     * <code>required bytes value = 2;</code>
     */
    boolean hasValue();
    /**
     * <code>required bytes value = 2;</code>
     */
    com.google.protobuf.ByteString getValue();
  }
  /**
   * Protobuf type {@code com.yahoo.ycsb.db.voldemort.Entry}
   */
  public static final class Entry extends
      com.google.protobuf.GeneratedMessage
      implements EntryOrBuilder {
    // Use Entry.newBuilder() to construct.
    private Entry(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Entry(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Entry defaultInstance;
    public static Entry getDefaultInstance() {
      return defaultInstance;
    }

    public Entry getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Entry(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              key_ = input.readBytes();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              value_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.yahoo.ycsb.db.voldemort.MsgProto.internal_static_com_yahoo_ycsb_db_voldemort_Entry_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.yahoo.ycsb.db.voldemort.MsgProto.internal_static_com_yahoo_ycsb_db_voldemort_Entry_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.yahoo.ycsb.db.voldemort.MsgProto.Entry.class, com.yahoo.ycsb.db.voldemort.MsgProto.Entry.Builder.class);
    }

    public static com.google.protobuf.Parser<Entry> PARSER =
        new com.google.protobuf.AbstractParser<Entry>() {
      public Entry parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Entry(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Entry> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required bytes key = 1;
    public static final int KEY_FIELD_NUMBER = 1;
    private com.google.protobuf.ByteString key_;
    /**
     * <code>required bytes key = 1;</code>
     */
    public boolean hasKey() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required bytes key = 1;</code>
     */
    public com.google.protobuf.ByteString getKey() {
      return key_;
    }

    // required bytes value = 2;
    public static final int VALUE_FIELD_NUMBER = 2;
    private com.google.protobuf.ByteString value_;
    /**
     * <code>required bytes value = 2;</code>
     */
    public boolean hasValue() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required bytes value = 2;</code>
     */
    public com.google.protobuf.ByteString getValue() {
      return value_;
    }

    private void initFields() {
      key_ = com.google.protobuf.ByteString.EMPTY;
      value_ = com.google.protobuf.ByteString.EMPTY;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasKey()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasValue()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, key_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, value_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, key_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, value_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.yahoo.ycsb.db.voldemort.MsgProto.Entry parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.yahoo.ycsb.db.voldemort.MsgProto.Entry parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.yahoo.ycsb.db.voldemort.MsgProto.Entry parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.yahoo.ycsb.db.voldemort.MsgProto.Entry parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.yahoo.ycsb.db.voldemort.MsgProto.Entry parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.yahoo.ycsb.db.voldemort.MsgProto.Entry parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.yahoo.ycsb.db.voldemort.MsgProto.Entry parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.yahoo.ycsb.db.voldemort.MsgProto.Entry parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.yahoo.ycsb.db.voldemort.MsgProto.Entry parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.yahoo.ycsb.db.voldemort.MsgProto.Entry parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.yahoo.ycsb.db.voldemort.MsgProto.Entry prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.yahoo.ycsb.db.voldemort.Entry}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.yahoo.ycsb.db.voldemort.MsgProto.EntryOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.yahoo.ycsb.db.voldemort.MsgProto.internal_static_com_yahoo_ycsb_db_voldemort_Entry_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.yahoo.ycsb.db.voldemort.MsgProto.internal_static_com_yahoo_ycsb_db_voldemort_Entry_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.yahoo.ycsb.db.voldemort.MsgProto.Entry.class, com.yahoo.ycsb.db.voldemort.MsgProto.Entry.Builder.class);
      }

      // Construct using com.yahoo.ycsb.db.voldemort.MsgProto.Entry.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        key_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        value_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.yahoo.ycsb.db.voldemort.MsgProto.internal_static_com_yahoo_ycsb_db_voldemort_Entry_descriptor;
      }

      public com.yahoo.ycsb.db.voldemort.MsgProto.Entry getDefaultInstanceForType() {
        return com.yahoo.ycsb.db.voldemort.MsgProto.Entry.getDefaultInstance();
      }

      public com.yahoo.ycsb.db.voldemort.MsgProto.Entry build() {
        com.yahoo.ycsb.db.voldemort.MsgProto.Entry result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.yahoo.ycsb.db.voldemort.MsgProto.Entry buildPartial() {
        com.yahoo.ycsb.db.voldemort.MsgProto.Entry result = new com.yahoo.ycsb.db.voldemort.MsgProto.Entry(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.key_ = key_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.value_ = value_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.yahoo.ycsb.db.voldemort.MsgProto.Entry) {
          return mergeFrom((com.yahoo.ycsb.db.voldemort.MsgProto.Entry)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.yahoo.ycsb.db.voldemort.MsgProto.Entry other) {
        if (other == com.yahoo.ycsb.db.voldemort.MsgProto.Entry.getDefaultInstance()) return this;
        if (other.hasKey()) {
          setKey(other.getKey());
        }
        if (other.hasValue()) {
          setValue(other.getValue());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasKey()) {
          
          return false;
        }
        if (!hasValue()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.yahoo.ycsb.db.voldemort.MsgProto.Entry parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.yahoo.ycsb.db.voldemort.MsgProto.Entry) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required bytes key = 1;
      private com.google.protobuf.ByteString key_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>required bytes key = 1;</code>
       */
      public boolean hasKey() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required bytes key = 1;</code>
       */
      public com.google.protobuf.ByteString getKey() {
        return key_;
      }
      /**
       * <code>required bytes key = 1;</code>
       */
      public Builder setKey(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        key_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required bytes key = 1;</code>
       */
      public Builder clearKey() {
        bitField0_ = (bitField0_ & ~0x00000001);
        key_ = getDefaultInstance().getKey();
        onChanged();
        return this;
      }

      // required bytes value = 2;
      private com.google.protobuf.ByteString value_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>required bytes value = 2;</code>
       */
      public boolean hasValue() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required bytes value = 2;</code>
       */
      public com.google.protobuf.ByteString getValue() {
        return value_;
      }
      /**
       * <code>required bytes value = 2;</code>
       */
      public Builder setValue(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        value_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required bytes value = 2;</code>
       */
      public Builder clearValue() {
        bitField0_ = (bitField0_ & ~0x00000002);
        value_ = getDefaultInstance().getValue();
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.yahoo.ycsb.db.voldemort.Entry)
    }

    static {
      defaultInstance = new Entry(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.yahoo.ycsb.db.voldemort.Entry)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_yahoo_ycsb_db_voldemort_Msg_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_yahoo_ycsb_db_voldemort_Msg_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_yahoo_ycsb_db_voldemort_Entry_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_yahoo_ycsb_db_voldemort_Entry_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n!src/main/resources/MsgProto.proto\022\033com" +
      ".yahoo.ycsb.db.voldemort\"8\n\003Msg\0221\n\005entry" +
      "\030\001 \003(\0132\".com.yahoo.ycsb.db.voldemort.Ent" +
      "ry\"#\n\005Entry\022\013\n\003key\030\001 \002(\014\022\r\n\005value\030\002 \002(\014B" +
      "\037\n\033com.yahoo.ycsb.db.voldemortH\001"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_com_yahoo_ycsb_db_voldemort_Msg_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_com_yahoo_ycsb_db_voldemort_Msg_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_yahoo_ycsb_db_voldemort_Msg_descriptor,
              new java.lang.String[] { "Entry", });
          internal_static_com_yahoo_ycsb_db_voldemort_Entry_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_com_yahoo_ycsb_db_voldemort_Entry_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_yahoo_ycsb_db_voldemort_Entry_descriptor,
              new java.lang.String[] { "Key", "Value", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
